image: node:9.11.1

link_validator:
  image: python:3.10-alpine
  script:
    - ./check_links.py


pages:
  cache:
    paths:
    - node_modules/

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
    - public

  only:
    - master
